source 'https://rubygems.org'

gem 'newrelic_rpm'
gem 'stackprof'
gem 'stackprof-webnav'
gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'bcrypt'

group :development do
  gem 'sinatra-contrib'
end
